### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by devnim** [liuch37/semantic-segmentation#2]
Hi,

I am running your code on raspberry pi 4 with 4GB ram. On just one image. I am getting am error message after the inference starts, saying "cannot allocate memory. You tried to allocate 251682400 bytes error code 12. 

I know the issue could be my weak device, but still, would you expect this issue on one image? 

What could be other potential causes? Also, what model parameters should I set for my device if you believe the issue is lack of RAM.

Update: I think I am getting this error message after this line "        scores = torch.zeros(1, num_class, segSize[0], segSize[1])"

The values of num_class is 150 and segSize is (2048,2048)

Thanks

**Comment by liuch37** [comment]
In this case I would suggest you to downsize your image after reading it, try to downsize until your machine can process it. Then resize it back after model inference is done.
